services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      timetracking_net:
        ipv4_address: 172.28.0.10

  mqtt-listener:
    build:
      context: ./MQTTService
      dockerfile: Dockerfile
    container_name: mqtt-listener
    depends_on:
      - mongodb
    volumes:
      - ./logs:/opt/loxberry/data/plugins/timetrackingplugin
    networks:
      timetracking_net:
        ipv4_address: 172.28.0.20

  webapp:
    build:
      context: ./Webapp
      dockerfile: Dockerfile
    container_name: webapp
    depends_on:
      - mongodb
    ports:
      - "8080:80"
    networks:
      timetracking_net:
        ipv4_address: 172.28.0.30
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI="mongodb://admin:adminpassword@172.28.0.10:27017"
      - SECRET_KEY="dfhgfjllkjmlkjlkmjgfjhgkjljkljkfxde"
    volumes:
      - ./logs:/app/logs
    networks:
      timetracking_net:
        ipv4_address: 172.28.0.15

volumes:
  mongodb_data:

networks:
  timetracking_net:
    ipam:
      config:
        - subnet: 172.28.0.0/16